### ISSUE TITLE
Feature request: being able to display the pictures in a random order

### ISSUE THREAD

**Issue by francoiscabrol** [Caleb9/syno-photo-frame#1]
Wow I have just try to build your app and it's running well on my raspberry pi zero 1 (32 bits)! thank you very much.
Using a synology photo album link is very clever and convenient 👍  

However one feature is missing: I have seen I can start the slideshow at a random photo, but do you plan to implement a way to choose the next photo randomly? Maybe you don't need it but I think it would be a nice improvement.

**Comment by francoiscabrol** [comment]
Or even better than totally random, it could be "start randomly" and then skip a random number of pictures (between 1 and 10 for instance) between each picture

**Comment by Caleb9** [comment]
Hi @francoiscabrol, glad you like the project and thanks for kind words :). Yeah I think it would be relatively easy to do. Give me some time and I'll see what I can do :+1:

**Comment by Caleb9** [comment]
@francoiscabrol try the [latest release 0.3.0](https://github.com/Caleb9/syno-photo-frame/releases/tag/0.3.0). Use `--order random` option to get photos displayed in random order (also look at `--help`, I replaced the `--random-start` option with `--order random-start`).

If you get to try it out, let me know how it works. Enjoy! :)

**Comment by francoiscabrol** [comment]
Thank you! I am assembling my frame, I am going to try the new version!

**Comment by francoiscabrol** [comment]
All good!! It is working perfectly well thank you!
