### ISSUE TITLE
blurry background fill

### ISSUE THREAD

**Issue by 3in1sl** [Caleb9/syno-photo-frame#14]
super great app.I love it.works fine and stable on my device. but I still have a little suggestion about the backguound.
is there any way to chose the black fill to replace blurry background? Or can I expect in the next version update?

**Comment by Caleb9** [comment]
Thanks! :)

Currently there's no way to disable the background, but it's a good idea for a switch. I'll look into it when I get the time :+1:

**Comment by Caleb9** [comment]
@3in1sl check out [Release 0.13.0](https://github.com/Caleb9/syno-photo-frame/releases/tag/0.13.0). Use `--background none` option to disable the blurry background. :)

**Comment by 3in1sl** [comment]
WOW! I can't believe it came so quickly! to me，it will be the perfect version now! love you~~~~
