### ISSUE TITLE
Can I start a debug output?

### ISSUE THREAD

**Issue by sks7g** [Caleb9/syno-photo-frame#16]
Now it has happened, the micro SD card has said goodbye, so no backup, reinstall.
Pi-OS Lite 04.07.2024, syno-foto-frame 0.12.1 , latest.

So far, so good, the shared link has not changed.
After starting, I only see the process, no output on the screen. 
Is there a --debug to find out what the process is doing?

**Comment by Caleb9** [comment]
Yes, run the program like this: `RUST_LOG=debug ./syno-photo-frame ...` You can try `trace` instead of `debug` for even more verbose output.
