### ISSUE TITLE
Very long interval between photos

### ISSUE THREAD

**Issue by jjeaton** [Caleb9/syno-photo-frame#17]
Hey thanks for making this, it's exactly what I was looking for.

I've tried a bunch of different interval values and it seems to take 60 seconds to change photos no matter what I choose. Is there a way to see when it's trying to switch and how long it's taking to download the images?

**Comment by Caleb9** [comment]
Hi @jjeaton.

You can prepend the command with `RUST_LOG=debug` or `RUST_LOG=trace` to log out some info to the console, see if there's anything indicating it's a slow network or NAS. However, considering there's a default request timeout of 30 seconds (you can control it with the `--timeout` option), I doubt that's the reason.

Another (more likely) possibility is that you have a very high resolution display connected, and RPi is struggling with scaling and blurring the background. You can use e.g. `htop` in another terminal to see the process is maxing out the CPU for about 60 seconds. If that's the case, then disabling the background (`--background none`) or, well, lowering resolution could help. Btw. which RPi model do you use?

Let me know if any of this helped. Thanks.

**Comment by jjeaton** [comment]
@Caleb9 super helpful thanks. The background blur was it! Once I disabled that, it's working perfectly. I'm using a Zero 2W. I'm using [a portable monitor](https://www.amazon.com/dp/B0B9NNWXVP) I found on Amazon that's 1080p although I may try and find a 4:3 aspect ratio one.

I was also having trouble getting it to run on boot, but after making this change it seems to be working there again, I increased the sleep amount to 90.

**Comment by Caleb9** [comment]
@jjeaton Nice! :) Just FYI I also use Zero 2W with a Full HD screen and it works fine with 30 second intervals (with blur) and 5 second sleep (for normal 3:2 aspect photos at least). So unless you intentionally have something else running on it that takes up resources, then maybe it's worth investigating why is it so slow on your device :thinking:
