### ISSUE TITLE
the image format could not be determined

### ISSUE THREAD

**Issue by miros077** [Caleb9/syno-photo-frame#8]
Hello, 

I have just installed version 0.7.0 and unfortunatelly I am getting fail message "The image format could not be determined". Share link is in format http://{myNasIP}:5000/mo/sharing/d6QunxSCC and is set to view for all with a link. 

Could you please give me advice where could be problem?

Thank you in advance!

**Comment by Caleb9** [comment]
Hi @miros077,

Can you please describe your setup in more detail?

- Are you able to view the album's photos in a normal web browser on another PC or your phone (to make sure the Synology Photos part is working as it should)
- Pi model
- System version, also Lite or Desktop edition (assuming Raspberry Pi OS)
- Did you start with clean installation of the system or an existing one?
- Is there any other customization, especially anything related to graphics (e.g. via raspi-config or `/boot/config.txt`)?

Also, you can try to execute the app like this:
```
RUST_LOG=debug syno-photo-frame https://YOUR_SHARING_LINK
```
to get more detailed log and post some of it here.

**Comment by miros077** [comment]
Hi Caleb9, 

I have updated Synology Photos and all of sudden all works with the same settings.

Than you very much for your support and great project!

**Comment by Caleb9** [comment]
@miros077 that's good to hear, thanks :). Do you by any chance recall which version of Synology Photos you had installed before the update? I'd like to make a note about supported versions.
